# Generated by Django 3.2 on 2021-05-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netconf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='fromdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='todate',
            field=models.DateField(),
        ),
    ]
