# Generated by Django 3.2 on 2021-05-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netconf', '0002_auto_20210501_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='fromdate',
            new_name='End_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='todate',
            new_name='Start_date',
        ),
        migrations.RemoveField(
            model_name='program',
            name='time',
        ),
        migrations.AddField(
            model_name='program',
            name='end_time',
            field=models.TimeField(default='15:00'),
        ),
        migrations.AddField(
            model_name='program',
            name='start_time',
            field=models.TimeField(default='14:00'),
        ),
    ]
