# Generated by Django 3.2 on 2021-05-01 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netconf', '0003_auto_20210501_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committeemember',
            name='venue',
        ),
    ]
