# Generated by Django 3.2 on 2021-05-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netconf', '0005_participant_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('presenter', models.CharField(choices=[('Attendee', 'Attendee'), ('Presenter', 'Presenter')], default='Attendee', max_length=150)),
                ('topic_to_Present', models.CharField(max_length=250)),
                ('topic_description', models.TextField(max_length=250)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
