# Generated by Django 3.2 on 2021-05-01 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netconf', '0006_researcher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Researcher',
        ),
    ]
