# Generated by Django 3.2 on 2021-05-02 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netconf', '0009_auto_20210502_0650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='topic',
        ),
    ]
